# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "cal-app-sam-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "cal-app-sam-dev"
region = "eu-central-2"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[prod]
[prod.global.parameters]
stack_name = "cal-app-sam"
parameter_overrides = """
  EnvType="prod"
  EventsTable="cal_events_no_lock"
  CFDistCNAME="adelboden.schlatter.net"
  CFDistViewerCertificate="arn:aws:acm:us-east-1:374093763622:certificate/40ae7d6a-4579-4ed1-8317-de645fb41539"
"""

[prod.build.parameters]
cached = true
parallel = true

[prod.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "cal-app-sam"
region = "eu-central-2"
image_repositories = []

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true