AWSTemplateFormatVersion: 2010-09-09
Description: >-
  cal-app-sam

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      # AllowCredentials: true  Uncomment only if you choose a specific origin instead of the * wildcard.

Parameters:
  # This is a DynamoDB table config
  EventsTable:
    Type: String
    Description: The DynamoDB table name to store events
    Default: cal_events

Resources:
  # This is a Lambda function config associated with the source code: listEvents.handler.js
  listEvents:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/listEvents.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: List events between two dates
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
